apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-discovery-hyper-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-discovery-hyper
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-discovery-hyper
    spec:
      containers:
        - name: discovery-hyper-container
          image: registry.hyper.mathematikoi.co/discovery.hyper
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-discovery-configmap
          ports:
            - containerPort: {{ .Values.configuration.port }}
              name: {{ .Release.Name }}-d-h-c-p
          imagePullPolicy: Always