apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-identity-configmap
data:
  IDENTITY_HYPER_PORT: {{ .Values.configuration.port | quote }}
  IDENTITY_HYPER_HOSTNAME_URL: {{ .Values.configuration.hostname_url | default (printf "http://identity.%s.%s" .Release.Name .Values.global.host) }}