apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-identity-ingress
spec:
  rules:
    - host: identity.{{ .Release.Name }}.{{ .Values.global.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ .Release.Name }}-identity-hyper-service
                port:
                  name: {{ .Release.Name }}-id-h-s-p
              {{- else }}
              serviceName: {{ .Release.Name }}-identity-hyper-service
              servicePort: {{ .Release.Name }}-id-h-s-p
              {{- end }}
