apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  APPLICATION_EXAMPLE_HYPER_PORT: {{ quote .Values.application.port }}
  INTERFACE_HYPER_PORT: {{ quote .Values.interface.port }}
  DISCOVERY_HYPER_PORT: {{ quote .Values.discovery.port }}

  IDENTITY_HYPER_HOSTNAME: {{ .Values.identity.hostname }}
  IDENTITY_HYPER_PORT: {{ quote .Values.identity.port }}
  IDENTITY_HYPER_PASSWORD: {{ .Values.identity.password }}
  
  AUTHORIZATION_HYPER_PORT: {{ quote .Values.authorization.port }}
  INTELLIGENCE_HYPER_PORT: {{quote .Values.intelligence.port }}
  AUTOMATION_HYPER_PORT: {{ quote .Values.automation.port }}
  INTERNATIONALIZATION_HYPER_PORT: {{ quote .Values.internationalization.port }}

  {{- range $index, $element := .Values.services }}
  {{ $element.name }}_HYPER_PORT: {{ quote $element.port }}
  {{- end }}