apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-application-hyper-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-application-hyper
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-application-hyper
    spec:
      containers:
        - name: application-hyper-container
          image: registry.hyper.mathematikoi.co/application.hyper:v1.0.0
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          ports:
            - containerPort: 1338
              name: {{ .Release.Name }}-a-h-c-p
          imagePullPolicy: Always