apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-identity-hyper-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-identity-hyper
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-identity-hyper
    spec:
      containers:
        - name: identity-hyper-container
          image: registry.hyper.mathematikoi.co/identity.hyper
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          ports:
            - containerPort: 1338
              name: {{ .Release.Name }}-id-h-c-p
          imagePullPolicy: Always